Added an optional boot delay, to help ensembles

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -53,13 +53,28 @@ if [ "${DATA_COUNT}" -lt 1 ] ; then
 	fi
 
 	# Remove leading zeros, just in case
-	MYID="$((10#${MYID}))"
+	MYID="$(( 10#${MYID} ))"
 	[ ${MYID} -ge 1 ] && [ ${MYID} -le 255 ] || fail "The MYID value must be in the range [1..255] (${MYID})"
 
 	zkServer-initialize.sh --force --myid=${MYID}
 fi
 
 say "Launching the main process"
+
+MAX_BOOT_DELAY="60"
+if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
+	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
+	if [ ${BOOT_DELAY} -gt 0 ] ; then
+		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
+		say "Applying a boot delay of ${BOOT_DELAY} seconds"
+		START="$(date +%s)"
+		while true ; do
+			DIFF="$(( $(date +%s) - START ))"
+			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
+			sleep 1 || fail "Boot delay aborted - exiting"
+		done
+	fi
+fi
 
 [ ${#} -gt 0 ] || set -- "start-foreground"
 EXE="${HOME_DIR}/bin/zkServer.sh"
